fps: 30
force_yes: false
io:
  dataset_name: AMARV
  filter_completed: true
  video_dir_path: /lsdf/data/activity/AMARV/run4_2023_01_27
  ego4d_download_dir: /lsdf/data/activity/AMARV/run4_2023_01_27
  uid_list: null
  video_limit: -1
  out_path: /local_data/tmp/run4_2023_01_27_features/omnivore
  debug_path: /local_data/tmp/run4_2023_01_27_features/omnivore/debug
  debug_mode: false
  exclude_no_audio: false
inference_config:
  device: cuda:0
  batch_size: 1
  num_workers: 10
  prefetch_factor: 3
  fps: 30
  frame_window: 32
  stride: 16
  include_audio: false
  include_video: true
  norm_config:
    normalize_audio: false
    resample_audio_rate: 16000
    resampling_method: "sinc_interpolation"
schedule_config:
  run_locally: false
  log_folder: slurm_log/%j
  timeout_min: 5000
  constraint: volta
  slurm_partition: pixar
  slurm_array_parallelism: 256
  gpus_per_node: 4
  cpus_per_task: 10
  overhead: 1.1
  time_per_forward_pass: 0.8
  schedule_time_per_node: 10.0
model_config:
  model_name: "omnivore_swinL_imagenet21k"
  input_type: "video"
  side_size: 256
  crop_size: 224
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
model_module_str: ego4d.features.models.omnivore
